Courses_HW_4/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace Courses_HW_4.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Courses_HW_4/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Components.Web;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Text.RegularExpressions;
using System.Xml.Linq;

namespace Courses_HW_4.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;
        public static bool Error { get; set; }
        public static string ErrorMessage { get; set; } = "";
        public static bool RemoveCookiesButtonDisabled { get; set; } = true;
        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RemoveCookiesButtonDisabled = Convert.ToBoolean(Request.Cookies["RemoveCookiesButtonDisabled"]);
        }
        public IActionResult OnPostRedirectToMain()
        {
            string name = Request.Form["Name"];
            string email = Request.Form["Email"];
            if(string.IsNullOrWhiteSpace(name) || !Regex.IsMatch(email, @"^[\w-\.]+@([\w-]+\.)+[\w-]{2,4}$"))
            {
                Error = true;
                ErrorMessage = "Field name or email was empty or email wasnt in correct format :(";
                return Page();
            }
            Error = false;
            Response.Cookies.Append("name", name);
            Response.Cookies.Append("email", email);
            Response.Cookies.Append("RemoveCookiesButtonDisabled", "false");
            RemoveCookiesButtonDisabled = false;
            return RedirectToPage("Main");
        }
        public void OnPostClearCookies()
        {
            Response.Cookies.Delete("name");
            Response.Cookies.Delete("email");
            Response.Cookies.Append("RemoveCookiesButtonDisabled", "true");
            RemoveCookiesButtonDisabled = true;
        }
    }
}

Courses_HW_4/Pages/Main.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Courses_HW_4.Pages
{
    public class MainModel : PageModel
    {
        public string? Name { get; set; }
        public string? Email { get; set; }

        public void OnGet()
        {
            Name = Request.Cookies["name"];
            Email = Request.Cookies["email"];
        }
    }
}

Courses_HW_4/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}
<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <div class="sendForm">
        <form method="post">
            <p>Your name</p> <input name = "Name" />
            <p>Your email</p> <input name = "Email" /> <br/>
            <button id="submitButton" asp-page-handler="RedirectToMain">Стать разработчиком</button>
            <button id="removeCookies" asp-page-handler="ClearCookies" disabled =@IndexModel.RemoveCookiesButtonDisabled> Очистить cookies </button>
        </form>
        @{
            if (IndexModel.Error)
            {
                <p id="error"> @IndexModel.ErrorMessage </p>
            }
        }
    </div> 
    <style>
        #submitButton {
            margin-top: 10px;
        }
        #error {
            color: red;
        }
    </style>
</div>

Courses_HW_4/Pages/Main.cshtml
@page
@model Courses_HW_4.Pages.MainModel
@{
    if(string.IsNullOrEmpty(Model.Name) || string.IsNullOrEmpty(Model.Email))
    {
       <h3>Ты не вошел перейти на <a href ="@Url.Page("Index")">страницу входа</a> </h3>
    }
    else
    {
        <h3> Я, @Model.Name, @Model.Email стал разработчиком ASP .NET. </h3>
    }
}

Courses_HW_4/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Courses_HW_4</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Courses_HW_4.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">Courses_HW_4</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Main">Main</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Courses_HW_4 - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>